version: '3.1'
services:
  postgresqldbservice:
    image: postgres
    container_name: postgrestest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  mysqldbservice:
    image: mysql/mysql-server
    container_name: mysqltest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"


docker exec -it mysqltest mysql -u root -pexample
docker exec -it postgrestest psql -U postgres -W postgres

docker stop  $(docker ps -a -q)
docker rm $(docker ps -a -q)
